package com.example.app.bussines;

public enum ShopEventType {
    CREATE_ORDER,
    CHECK_PAYMENT,
    CHECK_AVAILABILITY,
    REQUEST_PREPARE_PACKAGE,
    PACKAGE_READY,
    CHECK_POSTMAN_AVAILABILITY,
    REQUEST_POSTMAN,
    SEND_PACKAGE,
    PACKAGE_DELIVERED,

    RETURN_PACKAGE,
    CANCEL_ORDER,

}
